// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9-bX0IB8kCBe0iOEVf51sfvtltSxfcA',
    appId: '1:930028675510:web:a52ebda6fff83068906117',
    messagingSenderId: '930028675510',
    projectId: 'notebookapp-f4a56',
    authDomain: 'notebookapp-f4a56.firebaseapp.com',
    storageBucket: 'notebookapp-f4a56.appspot.com',
    measurementId: 'G-6HXD79T8GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMy2e1BqpVsQ-6snFLLUXQMd5ZXqemLs',
    appId: '1:930028675510:android:4bff7b7d9841c1e1906117',
    messagingSenderId: '930028675510',
    projectId: 'notebookapp-f4a56',
    storageBucket: 'notebookapp-f4a56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRya0NbImhcJ7Hnx7BEUMcFQR02nNdZyQ',
    appId: '1:930028675510:ios:e7fde2df73ff4730906117',
    messagingSenderId: '930028675510',
    projectId: 'notebookapp-f4a56',
    storageBucket: 'notebookapp-f4a56.appspot.com',
    iosClientId: '930028675510-0amaiamoqguqjsphn6st889aalka3o1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRya0NbImhcJ7Hnx7BEUMcFQR02nNdZyQ',
    appId: '1:930028675510:ios:88ca573159f01e16906117',
    messagingSenderId: '930028675510',
    projectId: 'notebookapp-f4a56',
    storageBucket: 'notebookapp-f4a56.appspot.com',
    iosClientId: '930028675510-nlsl4gcmbnfppp41eb8h0jmca1hr21lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebookApp.RunnerTests',
  );
}
